[window]
decorations = "Full"
opacity = 0.8
blur = false

[window.dimensions]
columns = 100
lines = 30

[window.position]
x = 300
y = 100

[window.padding]
x = 5
y = 5

[scrolling]
history = 10000

[font]
size = 12.0

[font.normal]
family = "RobotoMono Nerd Font"
style = "Medium"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[colors.primary]
foreground = "#e2c5d2"
background = "#1d0c13"

[colors.normal]
black = "#1d1f21"
red = "#e74789"
green = "#13a10e"
yellow = "#ad8c1b"
blue = "#81a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c5c8c6"

[colors.bright]
black = "#767676"
red = "#e74789"
green = "#23be51"
yellow = "#f3f9b2"
blue = "#3b78ff"
magenta = "#b4009e"
cyan = "#61d6d6"
white = "#f2f2f2"

[cursor]
style = { shape = "Beam", blinking = "On" }

[terminal]
shell = "pwsh -NoLogo"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

# This allows Ctrl+C to still kill processes (sending \u0003)
[[keyboard.bindings]]
key = "C"
mods = "Control"
chars = "\u0003"

[[keyboard.bindings]]
key = "T"
mods = "Control"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "Slash"
mods = "Control"
chars = "\u001f"