watch_stylesheet: true
watch_config: true
debug: false
bars:
  status-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 35
    widgets:
      left: ["home", "power_menu", "weather", "media", "pomodoro", "todo"]
      center: ["taskbar"]
      right:
        [
          "systray",
          "memory",
          "traffic",
          "wifi",
          "volume",
          "clock",
          "notifications",
        ]

widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span style='flex:auto'>\ue62a</span>" # \udb80\udf5c
      menu_labels:
        about: "\ue66A  About This PC"
        system: "\uF423  System Settings"
        task_manager: "\uf437  Task Manager"
        hibernate: "\uf28e  Hibernate"
        sleep: "\u23fe   Sleep"
        restart: "\uead2   Restart"
        shutdown: "\uf011   Shutdown"
        lock: "\uea75   Lock"
        logout: "\udb80\udf43   Logout"
      menu_list:
        - { title: "\uE617  User Home", path: "~" }
        - { title: "\udb80\udd20  Download", path: "~\\Downloads" }
        - { title: "\udb80\ude1a  Documents", path: "~\\Documents" }
        - { title: "\uf03e  Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      border_color: "System"
      round_corners_type: "normal"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300 # Milisecond
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\uea75", "Lock"]
        signout: ["\udb80\udf43", "Sign out"]
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        hibernate: ["\uf28e", "Hibernate"]
        cancel: ["\udb81\udf3a", "Cancel"]

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "<span>{icon}</span> {location}: {temp}, L {min_temp}, Max {max_temp}, Wind {wind}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807" # Get your free API key from https://www.weatherapi.com/
      update_interval: 3600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: "Darmstadt, Germany" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\uf4ee"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzardDay: "\uebaa"
        default: "\uebaa"
      # icons:
      #   sunnyDay: "‚òÄÔ∏è"
      #   clearNight: "üåô"
      #   cloudyDay: "‚õÖ"
      #   cloudyNight: "Ô∏è‚òÅÔ∏è"
      #   rainyDay: "üå¶Ô∏è"
      #   rainyNight: "üåßÔ∏è"
      #   snowyIcyDay: "‚ùÑÔ∏è"
      #   snowyIcyNight: "üå®Ô∏è"
      #   blizzardDay: "\ue362" #Óç¢
      #   blizzardNight: "\ue31c" #Óåú
      #   foggyDay: "üå´Ô∏è"
      #   foggyNight: "üò∂‚Äçüå´Ô∏è"
      #   thunderstormDay: "üå©Ô∏è"
      #   thunderstormNight: "‚õàÔ∏è"
      #   default: \uebaa"
      weather_card:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        icon_size: 48
        show_hourly_forecast: true # Set to False to disable hourly forecast
        time_format: "24h" # can be 12h or 24h
        hourly_point_spacing: 76
        hourly_icon_size: 32 # better to set 16, 32 or 64 for better quality
        icon_smoothing: true # should be true for smoother icon or false for sharper icon if using 16, 32 or 64 for hourly_icon_size
        temp_line_width: 2 # can be 0 to hide the temperature line

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: ""
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 30
        label_alt: 30
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 90
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 90
        max_artist_size: 40
        show_source: true
        show_volume_slider: true
      media_menu_icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      scrolling_label:
        enabled: true
        update_interval_ms: 20
        style: "left" # can be "left", "right", "bounce", "bounce-ease"
        separator: "  |  "
        label_padding: 10
        ease_slope: 10
        ease_pos: 0.3
        ease_min: 0.5

  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span> {session}/{total_sessions} - {status}"
      work_duration: 25
      break_duration: 5
      long_break_duration: 15
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: true
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        circle_background_color: "#09ffffff"
        circle_work_progress_color: "#88c0d0"
        circle_break_progress_color: "#a3be8c"
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  todo:
    type: "yasb.todo.TodoWidget"
    options:
      label: "\uf0ae {count}/{completed}"
      label_alt: "\uf0ae Tasks: {count}"
      # data_path: "~/Documents/my-todos.json"  # Optional: custom JSON file path
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
      icons:
        add: "+ New"
        edit: "Edit"
        delete: "Delete"
        date: "\ue641"
        category: "\uf412"
        checked: "\udb80\udd34"
        unchecked: "\udb80\udd30"
        sort: "\ueab4"
        no_tasks: "\uf4a0"
      categories:
        default:
          label: "General"
        soon:
          label: "Complete soon"
        today:
          label: "End of day"
        urgent:
          label: "Urgent"
        important:
          label: "Important"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      tooltip: false
      show_only_visible: false
      strict_filtering: false
      monitor_exclusive: false
      animation:
        enabled: true
      preview:
        enabled: true
        width: 450
        delay: 400
      ignore_apps:
        processes: []
        titles: []
        classes: []

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "\uf4bc {virtual_mem_used}/{virtual_mem_total}"
      label_alt: "\uefc5 VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "do_nothing"
        on_middle: "exec cmd /c Taskmgr"
        on_right: "toggle_label"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\udb83\udc9d</span>"
      label_alt: "<span>\udb83\udc9d</span> \ueab4 {download_speed} | \ueab7 {upload_speed}"
      update_interval: 1000
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:network-status"

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span> {wifi_strength}%"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_quick_settings"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      ethernet_label: "<span>{wifi_icon}</span>"
      ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
      ethernet_icon: "\ueba9"
      get_exact_wifi_strength: false # Optional. Will require location access permission if true.
      wifi_icons: [
          "\udb82\udd2e", # Icon for 0% strength
          "\udb82\udd1f", # Icon for 1-24% strength
          "\udb82\udd22", # Icon for 25-49% strength
          "\udb82\udd25", # Icon for 50-74% strength
          "\udb82\udd28", # Icon for 75-100% strength
        ]
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [1, 1]
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        wifi_icons_secured: ["\ue670", "\ue671", "\ue672", "\ue673"]
        wifi_icons_unsecured: ["\uec3c", "\uec3d", "\uec3e", "\uec3f"]

  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "‚óÄ"
      label_expanded: "‚ñ∂"
      label_position: "right" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: true

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      # label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\uf026" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\udb81\udd80" # Icon for 31-60% volume
        - "\uf029" # Icon for 61-100% volume
      callbacks:
        on_middle: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M %A %d.%m.%Y}"
      label_alt: "{%A, %d %B %Y, %H:%M}"
      locale: "de_DE"
      timezones: ["Europe/Berlin", "Asia/Ho_Chi_Minh", "America/New_York"]
      callbacks:
        on_middle: "do_nothing"
        on_right: "next_timezone"
      calendar:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        show_holidays: true
        show_week_numbers: true
        country_code: "DE"
        holiday_color: "#FF6464"

  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\udb84\udd6b</span> {count}"
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "do_nothing"
