watch_stylesheet: false
watch_config: false
debug: false
show_systray: false
update_check: false

bars:
  status:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    widgets:
      left: ["home", "power_menu", "weather", "media", "pomodoro", "todo"]
      center: ["taskbar"]
      right:
        [
          "systray",
          "language",
          "vscode",
          "memory",
          "traffic",
          "wifi",
          "volume",
          "clock",
          "notifications",
        ]

widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "\ue8e5"
      menu_labels:
        about: "\ue66A  About This PC"
        system: "\uF423  System Settings"
        task_manager: "\uf437  Task Manager"
        hibernate: "\uf28e  Hibernate"
        sleep: "\u23fe   Sleep"
        restart: "\uead2   Restart"
        shutdown: "\uf011   Shutdown"
        lock: "\uea75   Lock"
        logout: "\udb80\udf43   Logout"
      menu_list:
        - { title: "\uE617  User Home", path: "~" }
        - { title: "\udb80\udd20  Download", path: "~\\Downloads" }
        - { title: "\udb80\ude1a  Documents", path: "~\\Documents" }
        - { title: "\uf03e  Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      border_color: "System"
      round_corners_type: "normal"

  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300 # Milisecond
      button_row: 5 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\uf023", "Lock"] #
        signout: ["\uf08b", "Sign out"] # 
        shutdown: ["\uf011", "Shut Down"] # 
        restart: ["\uead2", "Restart"]
        cancel: ["\udb81\udf3a", "Cancel"]

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "<span>{icon}</span> {location}: {temp}, L {min_temp}, H {max_temp}, Wind {wind}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807" # Get your free API key from https://www.weatherapi.com/
      update_interval: 3600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      location: "Darmstadt, Germany" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\uf4ee"
        cloudyDay: "\uf0c2" #
        cloudyNight: "\ue226" #
        rainyDay: "\uef1e" #
        rainyNight: "\uef1b" #
        snowyDay: "\ue35f" #
        snowyIcyDay: "\ue35f" #
        snowyNight: "\ue327" #
        snowyIcyNight: "\ue327" #
        blizzardDay: "\uf2dc" #
        blizzardNight: "\uf2dc" #
        foggyDay: "\ue303" #
        foggyNight: "\ue346" #
        thunderstormDay: "\ue30e" #
        thunderstormNight: "\ue329" #
        default: "\uebaa"
      weather_card:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        icon_size: 48
        show_hourly_forecast: true # Set to False to disable hourly forecast
        time_format: "24h" # can be 12h or 24h
        hourly_point_spacing: 76
        hourly_icon_size: 32 # better to set 16, 32 or 64 for better quality
        icon_smoothing: true # should be true for smoother icon or false for sharper icon if using 16, 32 or 64 for hourly_icon_size
        temp_line_width: 2 # can be 0 to hide the temperature line

  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title} - {artist}"
      label_alt: ""
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 20
        label_alt: 20
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 90
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 90
        max_artist_size: 40
        show_source: true
        show_volume_slider: true
      media_menu_icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      scrolling_label:
        enabled: true
        update_interval_ms: 20
        style: "left" # can be "left", "right", "bounce", "bounce-ease"
        separator: "  |  "
        label_padding: 10
        ease_slope: 10
        ease_pos: 0.3
        ease_min: 0.5

  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "{icon} {remaining}"
      label_alt: "{icon} {session}/{total_sessions} - {status}"
      work_duration: 25
      break_duration: 5
      long_break_duration: 20
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: true
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\udb81\udd1f" #󰔟
        paused: "\udb86\udda0" #󱦠
        break: "\uf102" #
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        circle_background_color: "#1d0c13"
        circle_work_progress_color: "#ecafc9"
        circle_break_progress_color: "#a3be8c"
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"

  todo:
    type: "yasb.todo.TodoWidget"
    options:
      label: "\uf0ae {count}/{completed}"
      label_alt: "\uf0ae Tasks: {count}"
      # data_path: "~/Documents/my-todos.json"  # Optional: custom JSON file path
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
      icons:
        add: "+ New"
        edit: "\uf044" #
        delete: "️\udb80\uddb4" #󰆴
        date: "\ue641"
        category: "\uf412"
        checked: "\udb80\udd34"
        unchecked: "\udb80\udd30"
        sort: "\ueab4"
        no_tasks: "\uf4a0"
      categories:
        default:
          label: "Default"
        soon:
          label: "Soon"
        today:
          label: "Today"
        urgent:
          label: "Urgent"
        important:
          label: "Important"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"

  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      tooltip: false
      show_only_visible: false
      strict_filtering: false
      monitor_exclusive: false
      callbacks:
        on_middle: "close_app"
      animation:
        enabled: true
      preview:
        enabled: true
        width: 320
        delay: 400
      ignore_apps:
        processes: []
        titles: []
        classes: []

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "\uf4bc {virtual_mem_percent}%"
      label_alt: "\uf4bc VIRT: {virtual_mem_used}/{virtual_mem_total} SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: "do_nothing"
        on_middle: "exec cmd /c Taskmgr"
        on_right: "toggle_label"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90

  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\ueb6f" #
      label_expanded: "\ueb70" #
      label_position: "right" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: true

  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "{lang[language_code]}-{lang[country_code]}"
      label_alt: "{lang[full_name]}"
      update_interval: 10
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      language_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf11c"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  vscode:
    type: "yasb.vscode.VSCodeWidget"
    options:
      label: "\udb82\ude1e"
      menu_title: "<span style='font-weight:bold'>VScode</span> recents"
      max_field_size: 50
      folder_icon: "\uf07b" #
      file_icon: "\uf15b" #
      truncate_to_root_dir: false
      hide_folder_icon: false
      hide_file_icon: false
      max_number_of_folders: 30
      max_number_of_files: 0 # set to 0 if you only want folders
      modified_date_format: "Date modified: %Y-%m-%d %H:%M"
      cli_command: "code" # or "codium" or "windsurf" or any other CLI command to open the workspace
      callbacks:
        on_right: "do_nothing"
      state_storage_path: "C:\\Users\\huyen\\scoop\\apps\\vscode\\current\\data\\user-data\\User\\globalStorage\\state.vscdb"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        alignment: "center"
        offset_top: 6

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "\udb81\udef3" #󰛳
      label_alt: "\uf019 {download_speed} \uf093 {upload_speed}" #  
      update_interval: 1000
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
      callbacks:
        on_left: "toggle_menu"
        on_middle: "exec cmd.exe /c start ms-settings:network-status"
        on_right: "toggle_label"

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "{wifi_icon}"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "toggle_quick_settings"
        on_middle: "exec cmd.exe /c start ms-settings:network"
        on_right: "toggle_label"
      ethernet_label: "{wifi_icon}"
      ethernet_label_alt: "{wifi_icon} {ip_addr}"
      ethernet_icon: "\ueba9"
      get_exact_wifi_strength: false # Optional. Will require location access permission if true.
      wifi_icons: [
          "\udb82\udd2e", # Icon for 0% strength
          "\udb82\udd1f", # Icon for 1-24% strength
          "\udb82\udd22", # Icon for 25-49% strength
          "\udb82\udd25", # Icon for 50-74% strength
          "\udb82\udd28", # Icon for 75-100% strength
        ]
      menu_config:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        wifi_icons_secured: ["\ue670", "\ue671", "\ue672", "\ue673"]
        wifi_icons_unsecured: ["\uec3c", "\uec3d", "\uec3e", "\uec3f"]

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "{icon}"
      tooltip: false
      volume_icons:
        - "\ueee8" # Icon for muted 
        - "\uf026" # Icon for 0-10% volume 
        - "\uf027" # Icon for 11-30% volume 
        - "\uf027" # Icon for 31-60% volume 
        - "\uf028" # Icon for 61-100% volume 
      callbacks:
        on_left: "toggle_volume_menu"
        on_middle: "exec cmd.exe /c start ms-settings:sound"
        on_right: "toggle_mute"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"

  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%H:%M %a %d.%m}"
      label_alt: "{%H:%M, %A, %d %B %Y}"
      locale: "de_DE"
      timezones: ["Europe/Berlin", "Asia/Ho_Chi_Minh", "America/New_York"]
      alarm_icons:
        enabled: "\uf0f3"
        disabled: "\uf0a2"
        snooze: "\uf1f6"
      callbacks:
        on_middle: "toggle_label"
        on_right: "next_timezone"
      calendar:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        extended: True
        border_color: "System"
        alignment: "center"
        direction: "down"
        show_holidays: true
        show_week_numbers: true
        country_code: "DE"
        holiday_color: "#FF6464"

  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "\udb84\udd6b {count}"
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "do_nothing"
